# Workflow name
name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main", "hw2"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
               
      - uses: actions/checkout@v3
      - name: Lint with pylint
        run: |
          pip install pylint pytest
          pylint --rcfile=.pylintrc code/*.py
          
      - name: Run tests
        run: |          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          cd code
          python driver.py -e all
